name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        date_now: $(date +%s)
        git_hash: $(expr substr "$GITHUB_SHA" 0 5)
        go: "Go!"
      run: docker build . -t ghcr.io/ifsantos/node-api-service-lab:prod  && docker login -u ifsantos -p ${{ secrets.GITHUB_TOKEN }} ghcr.io && docker push ghcr.io/ifsantos/node-api-service-lab:prod 

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Publish the Built Docker image
      env:
        date_now: $(date +%s)
        git_hash: $(expr substr "$GITHUB_SHA" 0 5)
        go: "Go!"
      run: ls & echo 'Done' & echo ${git_hash} & echo ${go} & echo "Full sha ${{ GITHUB_SHA }}"
